[package]
name = "rox"
version = "0.1.0"
edition = "2021"

[features]
debug-trace-execution = []

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
